# Generated by Django 5.0.4 on 2024-06-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price', 'created_at', 'updated_at'], 'permissions': [('unpublish_a_product', 'Unpublish a product'), ('change_description_product,', 'Change description product'), ('change_category_product', 'Change category product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=True, help_text='Укажите статус публикации', null=True, verbose_name='Публикация'),
        ),
    ]
